export const navbar = [
    {
        navItem:'Dashboard',
        url:'/dashboard',
        isVisible:true,
        isIcon:true,
        icon:'dashboard',
        img:'assets/images/dashboard.svg'
    },
    {
        navItem:'Calender',
        url:'/calender',
        isVisible:true,
        isIcon:true,
        icon:'perm_contact_calendar',
        img:'assets/images/dashboard.svg'
    },
    {
        navItem:'Mailbox',
        url:'/mailbox',
        isVisible:true,
        isIcon:true,
        icon:'email',
        img:'assets/images/dashboard.svg'
    },
    {
        navItem:'File Manager',
        url:'/file-manager',
        isVisible:true,
        isIcon:true,
        icon:'account_balance_wallet',
        img:'assets/images/dashboard.svg'
    },
    {
        navItem:'Projects',
        url:'/projects',
        isVisible:true,
        isIcon:true,
        icon:'class',
        img:'assets/images/dashboard.svg'
    },
    {
        navItem:'Tasks',
        url:'/tasks',
        isVisible:true,
        isIcon:true,
        icon:'assignment',
        img:'assets/images/dashboard.svg'
    },
    {
        navItem:'Bugs',
        url:'/bugs',
        isVisible:true,
        isIcon:true,
        icon:'bug_report',
        img:'assets/images/dashboard.svg'
    },
    {
        navItem:'Opportunities',
        url:'/opportunities',
        isVisible:true,
        isIcon:true,
        icon:'dashboard',
        img:'assets/images/dashboard.svg'
    },
    {
        navItem:'Leads',
        url:'/leads',
        isVisible:true,
        isIcon:true,
        icon:'dashboard',
        img:'assets/images/dashboard.svg'
    },
    {
        navItem:'Sales',
        url:'/sales',
        isVisible:true,
        isIcon:true,
        icon:'dashboard',
        img:'assets/images/dashboard.svg'
    },
    {
        navItem:'Tickets',
        url:'/tickets',
        isVisible:true,
        isIcon:true,
        icon:'dashboard',
        img:'assets/images/dashboard.svg'
    },
    {
        navItem:'Knowledge Base',
        url:'/knowledge-base',
        isVisible:true,
        isIcon:true,
        icon:'dashboard',
        img:'assets/images/dashboard.svg'
    },
    {
        navItem:'Transactions',
        url:'/transactions',
        isVisible:true,
        isIcon:true,
        icon:'dashboard',
        img:'assets/images/dashboard.svg'
    },
    {
        navItem:'Clients',
        url:'/clients',
        isVisible:true,
        isIcon:true,
        icon:'dashboard',
        img:'assets/images/dashboard.svg'
    },
    {
        navItem:'Departments',
        url:'/departments',
        isVisible:true,
        isIcon:true,
        icon:'/dashboard',
        img:'assets/images/dashboard.svg'
    },
    {
        navItem:'Stocks',
        url:'/stocks',
        isVisible:true,
        isIcon:true,
        icon:'dashboard',
        img:'assets/images/dashboard.svg'
    },
    {
        navItem:'Attendance',
        url:'/attendance',
        isVisible:true,
        isIcon:true,
        icon:'dashboard',
        img:'assets/images/dashboard.svg'
    }
]